# Configuración de la Base de Datos (Neon PostgreSQL Desglosado)
spring.datasource.url=jdbc:postgresql://ep-floral-fog-apv56p4b-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TqM3wVFXZts8
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto donde correrá tu API de Turismo Barranca
server.port=8080